### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password1!"
}

### 로그인, 틀린 비밀번호로
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "asdf"
}

### 로그인, 맞는 비밀번호 및 계정, access token 전달
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password1!"
}